version: "3.9"

services:
  backend-api:
    build: ./backend
    container_name: backend-api
    ports:
      - "8000:8000"
    environment:
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    depends_on:
      opensearch:
        condition: service_healthy

  demo-app:
    build:
      context: ./demo-app
    container_name: demo-app
    environment:
      PORT: 8888
      LOG_LEVEL: info
    ports:
      - "8888:8888"
  test-backend:
    build: ./backend_ingest_test
    container_name: test-backend
    ports:
      - "8001:8001"
  
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend-api
      - logwatcher-ai

  logwatcher-ai:
    build: ./logwatcher_ai
    container_name: logwatcher-ai
    environment:
      - READ_FROM_DOCKER=false
      - BACKEND_API_URL=http://backend-api:8000/api/logs
      - BACKEND_POLL_INTERVAL=2.0
      - BACKEND_FETCH_SIZE=200
      - LOG_PATH=/app/demo.log
    volumes:
      - ./logwatcher_ai/OPENAI_API_KEY.txt:/app/OPENAI_API_KEY.txt:ro
    depends_on:
      - backend-api
    ports:
      - "8002:8002"

  agent:
    build: ./agent
    container_name: log_forwarding_agent
    environment:
      CONFIG_PATH: "/etc/agent/config.yaml"
    volumes:
      - ./agent/config.yaml:/etc/agent/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - demo-app
    ports:
    - "9000:9000"

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "9200:9200"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s >/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s

  #opensearch-dashboards:
  #  image: opensearchproject/opensearch-dashboards:2.11.0
  #  container_name: opensearch-dashboards
  #  environment:
  #    - OPENSEARCH_HOSTS=["http://opensearch:9200"]
  #    - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
  #  ports:
  #    - "5601:5601"
  #  depends_on:
  #    - opensearch

volumes:
  opensearch-data:
